<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PanenSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // User 1 - berbagai data panen tahun 2026

            [
                'user_id' => 1,
                'tanaman_id' => 1,
                'lahan_id' => 1,
                'tanggal_panen' => '2026-01-15',
                'jumlah_panen' => 400,
                'satuan' => 'kg',
                'harga_per_kg' => 5500,
                'total_nilai' => 2200000,
                'kualitas' => 'Baik',
                'cuaca' => 'Cerah',
                'catatan' => 'Panen perdana tahun ini',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 2,
                'lahan_id' => 3,
                'tanggal_panen' => '2026-01-28',
                'jumlah_panen' => 250,
                'satuan' => 'kg',
                'harga_per_kg' => 4000,
                'total_nilai' => 1000000,
                'kualitas' => 'Baik',
                'cuaca' => 'Berawan',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'user_id' => 1,
                'tanaman_id' => 1,
                'lahan_id' => 2,
                'tanggal_panen' => '2026-02-10',
                'jumlah_panen' => 350,
                'satuan' => 'kg',
                'harga_per_kg' => 5500,
                'total_nilai' => 1925000,
                'kualitas' => 'Sangat Baik',
                'cuaca' => 'Cerah',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 3,
                'lahan_id' => 5,
                'tanggal_panen' => '2026-02-20',
                'jumlah_panen' => 80,
                'satuan' => 'kg',
                'harga_per_kg' => 30000,
                'total_nilai' => 2400000,
                'kualitas' => 'Baik',
                'cuaca' => 'Cerah',
                'catatan' => 'Harga bagus',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 2,
                'lahan_id' => 4,
                'tanggal_panen' => '2026-02-25',
                'jumlah_panen' => 220,
                'satuan' => 'kg',
                'harga_per_kg' => 4000,
                'total_nilai' => 880000,
                'kualitas' => 'Cukup',
                'cuaca' => 'Hujan',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'user_id' => 1,
                'tanaman_id' => 1,
                'lahan_id' => 1,
                'tanggal_panen' => '2026-03-05',
                'jumlah_panen' => 320,
                'satuan' => 'kg',
                'harga_per_kg' => 5200,
                'total_nilai' => 1664000,
                'kualitas' => 'Baik',
                'cuaca' => 'Cerah Berawan',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 5,
                'lahan_id' => 5,
                'tanggal_panen' => '2026-03-18',
                'jumlah_panen' => 200,
                'satuan' => 'kg',
                'harga_per_kg' => 8000,
                'total_nilai' => 1600000,
                'kualitas' => 'Sangat Baik',
                'cuaca' => 'Cerah',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'user_id' => 1,
                'tanaman_id' => 1,
                'lahan_id' => 2,
                'tanggal_panen' => '2026-04-12',
                'jumlah_panen' => 380,
                'satuan' => 'kg',
                'harga_per_kg' => 5500,
                'total_nilai' => 2090000,
                'kualitas' => 'Baik',
                'cuaca' => 'Cerah',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 3,
                'lahan_id' => 3,
                'tanggal_panen' => '2026-04-20',
                'jumlah_panen' => 140,
                'satuan' => 'kg',
                'harga_per_kg' => 28000,
                'total_nilai' => 3920000,
                'kualitas' => 'Sangat Baik',
                'cuaca' => 'Cerah',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'user_id' => 1,
                'tanaman_id' => 1,
                'lahan_id' => 1,
                'tanggal_panen' => '2026-05-15',
                'jumlah_panen' => 420,
                'satuan' => 'kg',
                'harga_per_kg' => 5200,
                'total_nilai' => 2184000,
                'kualitas' => 'Baik',
                'cuaca' => 'Cerah',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 2,
                'lahan_id' => 3,
                'tanggal_panen' => '2026-05-15',
                'jumlah_panen' => 300,
                'satuan' => 'kg',
                'harga_per_kg' => 3800,
                'total_nilai' => 1140000,
                'kualitas' => 'Cukup',
                'cuaca' => 'Berawan',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 1,
                'lahan_id' => 2,
                'tanggal_panen' => '2026-05-20',
                'jumlah_panen' => 700,
                'satuan' => 'kg',
                'harga_per_kg' => 5200,
                'total_nilai' => 3640000,
                'kualitas' => 'Baik',
                'cuaca' => 'Cerah Berawan',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 2,
                'lahan_id' => 4,
                'tanggal_panen' => '2026-05-20',
                'jumlah_panen' => 300,
                'satuan' => 'kg',
                'harga_per_kg' => 3800,
                'total_nilai' => 1140000,
                'kualitas' => 'Baik',
                'cuaca' => 'Berawan',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 1,
                'lahan_id' => 2,
                'tanggal_panen' => '2026-05-28',
                'jumlah_panen' => 280,
                'satuan' => 'kg',
                'harga_per_kg' => 5500,
                'total_nilai' => 1540000,
                'kualitas' => 'Cukup',
                'cuaca' => 'Hujan',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 3,
                'lahan_id' => 3,
                'tanggal_panen' => '2026-05-28',
                'jumlah_panen' => 120,
                'satuan' => 'kg',
                'harga_per_kg' => 30000,
                'total_nilai' => 3600000,
                'kualitas' => 'Baik',
                'cuaca' => 'Cerah',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'user_id' => 1,
                'tanaman_id' => 2,
                'lahan_id' => 4,
                'tanggal_panen' => '2026-06-05',
                'jumlah_panen' => 350,
                'satuan' => 'kg',
                'harga_per_kg' => 4000,
                'total_nilai' => 1400000,
                'kualitas' => 'Baik',
                'cuaca' => 'Cerah Berawan',
                'catatan' => '',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'user_id' => 1,
                'tanaman_id' => 1,
                'lahan_id' => 1,
                'tanggal_panen' => '2026-06-10',
                'jumlah_panen' => 850,
                'satuan' => 'kg',
                'harga_per_kg' => 5500,
                'total_nilai' => 4675000,
                'kualitas' => 'Sangat Baik',
                'cuaca' => 'Cerah',
                'catatan' => 'Hasil terbaik musim ini',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('panen')->insertBatch($data);
    }
}